# Travis CI script

language: c

sudo: false

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_12.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_12.04/Release.key'
    packages:
    - generator-scripting-language
    - libczmq-dev

#   Build and check this project
script:
- ./autogen.sh && ./configure && make distcheck
